#!/bin/sh

case "$1" in
    start)
        echo "loading aesdchar device driver"
		aesdchar_load
        echo "Starting ldd modules"
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Stopping ldd modules"
        scull_unload
        module_unload faulty
        rmmod hello
        echo "unloading aesdchar device driver"
		aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac